"use client";
import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Trash2, Share2, LogOut, BrainCircuit, History, AlertTriangle } from "lucide-react";

// 1. Define the Types
interface SimulationResult {
  risk_percentage: number;
  worst_case: string;
  likely_case: string;
  healthy_outcome: string;
  suggestions: string[];
}

interface HistoryItem extends SimulationResult {
  id: number;
  prompt: string;
  username: string;
  timestamp: string;
}

export default function Home() {
  // 2. All State Variables
  const [user, setUser] = useState<string | null>(null);
  const [emailInput, setEmailInput] = useState("");
  const [prompt, setPrompt] = useState("");
  const [result, setResult] = useState<SimulationResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState<HistoryItem[]>([]);

  // 3. Authentication & Initialization Logic
  useEffect(() => {
    const savedUser = localStorage.getItem("decision_user");
    if (savedUser) setUser(savedUser);
  }, []);

  useEffect(() => {
    if (user) fetchHistory();
  }, [user]);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (!emailInput.trim()) return;
    localStorage.setItem("decision_user", emailInput);
    setUser(emailInput);
  };

  const logout = () => {
    localStorage.removeItem("decision_user");
    setUser(null);
    setHistory([]);
    setResult(null);
  };

  // 4. API Interaction Logic
  const fetchHistory = async () => {
    if (!user) return;
    try {
      const res = await fetch(`/api/history/${user}`);
      if (res.ok) {
        const data = await res.json();
        setHistory(data);
      }
    } catch (error) {
      console.error("Error fetching history:", error);
    }
  };

  const analyzeDecision = async () => {
    if (!prompt.trim() || !user) return;
    setLoading(true);
    try {
      const response = await fetch("/api/predict", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt, username: user }),
      });
      if (!response.ok) throw new Error("Analysis failed");
      const data = await response.json();
      setResult(data);
      fetchHistory(); 
    } catch (error) {
      alert("Error: Backend is not responding.");
    }
    setLoading(false);
  };

  const copyToClipboard = () => {
    if (!result) return;
    const text = `🚀 Decision Analysis: ${prompt}\n\nRisk Level: ${result.risk_percentage}%\n\nWorst Case: ${result.worst_case}\nLikely Case: ${result.likely_case}\nHealthy Outcome: ${result.healthy_outcome}\n\nGenerated by StrategyEngine AI`;
    navigator.clipboard.writeText(text);
    alert("Analysis copied to clipboard!");
  };

  const deleteItem = (id: number) => {
      setHistory(history.filter(item => item.id !== id));
  };

  // 5. Render Login UI
  if (!user) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-[#0f172a] text-white p-4">
        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="p-10 bg-slate-800/50 backdrop-blur-xl border border-slate-700 rounded-3xl shadow-2xl w-full max-w-md"
        >
          <div className="flex justify-center mb-6">
            <div className="p-4 bg-blue-600 rounded-2xl shadow-lg shadow-blue-500/20">
              <BrainCircuit size={40} />
            </div>
          </div>
          <h1 className="text-3xl font-bold text-center mb-2">StrategyEngine</h1>
          <p className="text-slate-400 text-center text-sm mb-8">AI-Powered Risk & Outcome Simulation</p>
          <form onSubmit={handleLogin} className="space-y-4">
            <input 
              type="text" placeholder="Enter Username" 
              className="w-full p-4 rounded-xl bg-slate-900/50 border border-slate-700 focus:ring-2 focus:ring-blue-500 outline-none transition-all text-white"
              value={emailInput} onChange={(e) => setEmailInput(e.target.value)} required
            />
            <button className="w-full py-4 bg-blue-600 hover:bg-blue-500 rounded-xl font-bold transition-all shadow-lg shadow-blue-600/20">
              Access Dashboard
            </button>
          </form>
        </motion.div>
      </div>
    );
  }

  // 6. Render Dashboard UI
  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-900 pb-20">
      <nav className="sticky top-0 z-10 bg-white/80 backdrop-blur-md border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <BrainCircuit className="text-blue-600" />
            <span className="font-black text-xl tracking-tight">StrategyEngine</span>
          </div>
          <div className="flex items-center gap-4">
            <span className="hidden md:block text-sm font-medium text-slate-500">{user}</span>
            <button onClick={logout} className="p-2 hover:bg-red-50 text-red-500 rounded-full transition-colors">
              <LogOut size={20} />
            </button>
          </div>
        </div>
      </nav>

      <main className="max-w-6xl mx-auto px-6 mt-10 grid grid-cols-1 lg:grid-cols-3 gap-10">
        <div className="lg:col-span-2 space-y-8">
          <section className="bg-white p-8 rounded-[2rem] shadow-sm border border-slate-200">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <span className="p-1.5 bg-blue-100 text-blue-600 rounded-lg text-sm">1</span>
              Define Your Scenario
            </h2>
            <textarea
              className="w-full p-5 bg-slate-50 border border-slate-200 rounded-2xl h-32 focus:ring-2 focus:ring-blue-500 outline-none transition-all text-lg"
              placeholder="Example: Should I invest $5k in Bitcoin?"
              value={prompt} onChange={(e) => setPrompt(e.target.value)}
            />
            <button
              onClick={analyzeDecision} disabled={loading || !prompt}
              className="w-full mt-4 py-5 bg-slate-900 text-white rounded-2xl font-bold text-lg hover:bg-slate-800 disabled:opacity-50 transition-all shadow-xl shadow-slate-900/10"
            >
              {loading ? "Crunching Data..." : "Run AI Simulation"}
            </button>
          </section>

          <AnimatePresence>
            {result && (
              <motion.section 
                initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                className="bg-white p-8 rounded-[2rem] shadow-xl border border-blue-100 relative overflow-hidden"
              >
                <div className="absolute top-0 left-0 w-2 h-full bg-blue-600" />
                <div className="flex justify-between items-start mb-8">
                  <div>
                    <h2 className="text-2xl font-black">Simulation Results</h2>
                    <p className="text-slate-500">Professional Risk Audit</p>
                  </div>
                  <button onClick={copyToClipboard} className="p-3 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors text-slate-600">
                    <Share2 size={20} />
                  </button>
                </div>

                <div className="mb-10">
                    <div className="flex justify-between mb-2 items-end">
                        <span className="text-sm font-bold uppercase tracking-wider text-slate-400">Risk Factor</span>
                        <span className={`text-4xl font-black ${result.risk_percentage > 60 ? 'text-red-500' : 'text-emerald-500'}`}>
                            {result.risk_percentage}%
                        </span>
                    </div>
                    <div className="w-full bg-slate-100 h-4 rounded-full overflow-hidden">
                        <motion.div 
                          initial={{ width: 0 }} animate={{ width: `${result.risk_percentage}%` }}
                          className={`h-full rounded-full ${result.risk_percentage > 60 ? 'bg-red-500' : 'bg-emerald-500'}`}
                        />
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                  <ResultCard title="Worst Case" text={result.worst_case} type="error" />
                  <ResultCard title="Likely Case" text={result.likely_case} type="warning" />
                  <ResultCard title="Healthy Outcome" text={result.healthy_outcome} type="success" />
                </div>

                <div className="bg-slate-50 p-6 rounded-2xl">
                  <h4 className="font-bold mb-4 flex items-center gap-2">
                    <AlertTriangle size={18} className="text-amber-500" />
                    Strategic Recommendations
                  </h4>
                  <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {result.suggestions.map((s, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-slate-600 text-left">
                        <span className="min-w-[6px] h-[6px] rounded-full bg-blue-500 mt-2" />
                        {s}
                      </li>
                    ))}
                  </ul>
                </div>
              </motion.section>
            )}
          </AnimatePresence>
        </div>

        <div className="space-y-6">
            <div className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-200 h-fit">
                <h3 className="font-bold flex items-center gap-2 mb-6 text-left">
                    <History size={18} className="text-blue-600" />
                    Audit Trail
                </h3>
                <div className="space-y-3">
                    {history.length === 0 && <p className="text-slate-400 text-sm italic">No history.</p>}
                    {history.map((h) => (
                        <div key={h.id} className="group p-4 bg-slate-50 border border-slate-100 rounded-2xl hover:border-blue-200 transition-all text-left">
                            <div className="flex justify-between items-start mb-1">
                                <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${h.risk_percentage > 60 ? 'bg-red-100 text-red-600' : 'bg-emerald-100 text-emerald-600'}`}>
                                    {h.risk_percentage}% RISK
                                </span>
                                <button onClick={() => deleteItem(h.id)} className="opacity-0 group-hover:opacity-100 text-slate-300 hover:text-red-500 transition-all">
                                    <Trash2 size={14} />
                                </button>
                            </div>
                            <p className="text-xs font-bold text-slate-700 line-clamp-2">{h.prompt}</p>
                            <p className="text-[10px] text-slate-400 mt-2">{new Date(h.timestamp).toLocaleDateString()}</p>
                        </div>
                    ))}
                </div>
            </div>
        </div>
      </main>
    </div>
  );
}

function ResultCard({ title, text, type }: { title: string, text: string, type: 'error' | 'warning' | 'success' }) {
    const colors = {
        error: "bg-red-50 border-red-100 text-red-700",
        warning: "bg-amber-50 border-amber-100 text-amber-700",
        success: "bg-emerald-50 border-emerald-100 text-emerald-700"
    };
    return (
        <div className={`p-5 rounded-2xl border ${colors[type]} transition-all hover:shadow-md text-left`}>
            <p className="text-[10px] font-black uppercase tracking-widest mb-1 opacity-70">{title}</p>
            <p className="text-xs leading-relaxed font-medium">{text}</p>
        </div>
    );
}